[phases.setup]
nixPkgs = ["jdk11", "gradle"]

[phases.build]
cmds = ["./gradlew build -x test"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=railway -jar build/libs/delivery-app.jar"