spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:1234}

  jpa:
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/delivery}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12