spring:
  rabbitmq:
    host: ${CLOUDAMQP_HOST:localhost}
    port: ${CLOUDAMQP_PORT:5672}
    username: ${CLOUDAMQP_USERNAME:admin}
    password: ${CLOUDAMQP_PASSWORD:1234}
    virtual-host: ${CLOUDAMQP_VHOST:/}
    connection-timeout: 30000
    template:
      retry:
        enabled: true
        initial-interval: 3000
        max-attempts: 3

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          url: ${DATABASE_URL}
        hbm2ddl:
          auto: create
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    hikari:
      maximum-pool-size: 1
      minimum-idle: 0
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      initialization-fail-timeout: -1
      auto-commit: true

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.delivery: DEBUG