spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:1234}

  jpa:
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${DB_USER:root}
    password: ${DB_PASS:1234}

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12