spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASS:1234}

  jpa:
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
  datasource:
    url: jdbc:postgresql://trolley.proxy.rlwy.net:30915/railway?user=postgres&password=nHdxFHgzdkBLEFhdubLgEpOwoEMwbXOn
    driver-class-name: org.postgresql.Driver

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12