spring:
  rabbitmq:
    host: ${CLOUDAMQP_HOST:localhost}
    port: ${CLOUDAMQP_PORT:5672}
    username: ${CLOUDAMQP_USERNAME:admin}
    password: ${CLOUDAMQP_PASSWORD:1234}
    virtual-host: ${CLOUDAMQP_VHOST:/}

  jpa:
    show-sql: false
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 900000

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.delivery: DEBUG